## File generated by the BNF Converter (bnfc 2.9.5).

CC=g++ -g
CCFLAGS=--ansi -std=c++20 -W -Wall -Wsign-conversion -Wno-unused-parameter -Wno-unused-function -Wno-unneeded-internal-declaration

FLEX=flex
FLEX_OPTS=-Platte_cpp_

BISON=bison
BISON_OPTS=-t -platte_cpp_

OBJS=Absyn.o Buffer.o Lexer.o Parser.o Printer.o

.PHONY : clean distclean

all : TestLatteCPP

run :
	./TestLatteCPP < /home/bartlomiej-zamojtel/Programming/Zadanie_2_Latte_Compiler/Tests/test001.lat

clean :
	rm -f *.o TestLatteCPP LatteCPP.aux LatteCPP.log LatteCPP.pdf LatteCPP.dvi LatteCPP.ps LatteCPP

distclean : clean
	rm -f Absyn.C Absyn.H Buffer.C Buffer.H Test.C Bison.H Parser.C Parser.H ParserError.H LatteCPP.y Lexer.C LatteCPP.l Skeleton.C Skeleton.H Printer.C Printer.H Makefile LatteCPP.tex

TestLatteCPP : ${OBJS} Test.o
	@echo "Linking TestLatteCPP..."
	${CC} ${OBJS} Test.o -o TestLatteCPP

Absyn.o : Absyn.C Absyn.H
	${CC} ${CCFLAGS} -c Absyn.C

Buffer.o : Buffer.C Buffer.H
	${CC} ${CCFLAGS} -c Buffer.C

Lexer.C : LatteCPP.l
	${FLEX} ${FLEX_OPTS} -oLexer.C LatteCPP.l

Parser.C Bison.H : LatteCPP.y
	${BISON} ${BISON_OPTS} LatteCPP.y -o Parser.C

Lexer.o : CCFLAGS+=-Wno-sign-conversion

Lexer.o : Lexer.C Bison.H
	${CC} ${CCFLAGS} -c Lexer.C

Parser.o : Parser.C Absyn.H Bison.H
	${CC} ${CCFLAGS} -c Parser.C

Printer.o : Printer.C Printer.H Absyn.H
	${CC} ${CCFLAGS} -c Printer.C

Skeleton.o : Skeleton.C Skeleton.H Absyn.H
	${CC} ${CCFLAGS} -Wno-unused-parameter -c Skeleton.C

Test.o : Test.C Parser.H Printer.H Absyn.H
	${CC} ${CCFLAGS} -c Test.C
